name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build CSS
        uses: gha-utilities/sass-build@v0.3.4
        with:
          source: index.scss
          destination: index.css
      - name: Copy to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_IP }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: apps
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          target: ${{ secrets.DEPLOY_DIR }}
          rm: true
          source: index.html,index.css,assets
