name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - name: Build
        run: |
          npm install
          npm run build
      - name: Copy to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_IP }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: apps
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          target: ${{ secrets.DEPLOY_DIR }}
          source: index.html,index.css,assets
